name       : gtk2hs-buildtools
version    : 0.13.2.2
release    : 1
source     :
    - http://hackage.haskell.org/package/gtk2hs-buildtools-0.13.2.2/gtk2hs-buildtools-0.13.2.2.tar.gz : c5e4b59f8711ec4e4e25a91ce4213c5396dd0b56179751ed6da255ac35edfb4b
license    : GPL-2.0
component  : programming.haskell
summary    : This package provides a set of helper programs necessary to build the Gtk2Hs suite of libraries.
description: |
    This package provides a set of helper programs necessary to build the Gtk2Hs suite of libraries.
builddeps  :
    - haskell-alex
    - haskell-cabal-install
    - haskell-happy
    - haskell-hashtables
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
