name       : gtk2hs-buildtools
version    : 0.13.4.0
release    : 6
source     :
    - https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.4.0/gtk2hs-buildtools-0.13.4.0.tar.gz : 0f3e6ba90839efd43efe8cecbddb6478a55e2ce7788c57a0add4df477dede679
license    : GPL-2.0
component  : programming.haskell
summary    : This package provides a set of helper programs necessary to build the
    Gtk2Hs suite of libraries.
description: |
    This package provides a set of helper programs necessary to build the Gtk2Hs suite of libraries.
builddeps  :
    - haskell-alex
    - haskell-cabal-install
    - haskell-happy
    - haskell-hashtables
    - haskell-random
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
