name       : gtk2hs-buildtools
version    : 0.13.8.0
release    : 7
source     :
    - https://hackage.haskell.org/package/gtk2hs-buildtools-0.13.8.0/gtk2hs-buildtools-0.13.8.0.tar.gz : 8dbb7dbf004e45e48aa77153bc780120d99a329c6bde76618d46b2a4f3bb8598
license    : GPL-2.0-only
component  : programming.haskell
summary    : This package provides a set of helper programs necessary to build the Gtk2Hs suite of libraries.
description: |
    This package provides a set of helper programs necessary to build the Gtk2Hs suite of libraries.
builddeps  :
    - haskell-alex
    - haskell-cabal-install
    - haskell-happy
    - haskell-hashtables-devel
    - haskell-random-devel
rundeps    :
    - devel:
        - haskell-hashtables-devel
        - haskell-random-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
